export const NOTION_DATABASE_PROJECTS_ID = process.env.NOTION_DATABASE_PROJECTS_ID
export const NOTION_TOKEN = process.env.NOTION_TOKEN
export const NOTION_DATABASE_MEMBERS_ID = process.env.NOTION_DATABASE_MEMBERS_ID
export const NOTION_DATABASE_ACTIVITYS_ID = process.env.NOTION_DATABASE_ACTIVITYS_ID